"use client";
import { useState } from "react";
import { computeFeeAmount, computeFuelCostPerKm, computeLitersFromPurchase, formatBRL, toNumber, todayISO, type ExtraExpense } from "@/lib/utils";
import ExtraExpenses from "./ExtraExpenses";
import MaintenanceExpenses, { type MaintenanceItem } from "./MaintenanceExpenses";
import CardDeLucro from "./CardDeLucro";
import StickyLaunchIntelligence from "./StickyLaunchIntelligence";
import { saveEntry } from "@/app/actions";

type Mode="withFee"|"net"; type Props={initialDate?:string;initialMonthProfit?:number}; type SavedCard={profit:number;km:number;hours:number;profitPerKm:number|null;costPerKm:number|null};
const fmtL=(v:number)=>v.toLocaleString("pt-BR",{minimumFractionDigits:2,maximumFractionDigits:3}); const fmtCost=(v:number|null)=>v===null?"—":`${formatBRL(v)} / km`;
function verdict(profit:number,km:number,profitKm:number|null,costKm:number|null,has:boolean){if(!has)return{tone:"neutral",text:"Lance o dia e descubra se sobrou dinheiro de verdade."};if(profit<=0)return profit===0?{tone:"amber",text:"🟡 Hoje você ficou no zero a zero: trabalhou pra pagar o carro."}:{tone:"red",text:`🔴 Hoje você PAGOU PRA TRABALHAR: faltaram ${formatBRL(Math.abs(profit))}.`};return{tone:"green",text:`🟢 Hoje você LUCROU ${formatBRL(profit)}.`};}
export default function EntryForm({initialDate=todayISO(),initialMonthProfit=0}:Props){
 const [mode,setMode]=useState<Mode>("withFee"),[date,setDate]=useState(initialDate),[gross,setGross]=useState(0),[fee,setFee]=useState(0),[netFare,setNetFare]=useState(0),[gas,setGas]=useState(0),[alcohol,setAlcohol]=useState(0),[gasPrice,setGasPrice]=useState(0),[alcoholPrice,setAlcoholPrice]=useState(0),[kmInitial,setKmInitial]=useState(0),[kmFinal,setKmFinal]=useState(0),[hours,setHours]=useState(0),[consumption,setConsumption]=useState(0),[maintenanceItems,setMaintenanceItems]=useState<MaintenanceItem[]>([]),[extras,setExtras]=useState<ExtraExpense[]>([]),[monthProfit,setMonthProfit]=useState(initialMonthProfit),[status,setStatus]=useState(""),[savedCard,setSavedCard]=useState<SavedCard|null>(null);
 const kmDriven=Math.max(0,kmFinal-kmInitial),fareNet=mode==="withFee"?gross*(1-fee/100):netFare,feeAmount=mode==="withFee"?computeFeeAmount({gross_amount:gross,fee_percent:fee}):0,gasLiters=computeLitersFromPurchase(gas,gasPrice),alcoholLiters=computeLitersFromPurchase(alcohol,alcoholPrice),suppliedLiters=gasLiters+alcoholLiters,weightedPrice=suppliedLiters>0?(gas+alcohol)/suppliedLiters:0,consumedLiters=kmDriven>0&&consumption>0?kmDriven/consumption:0,consumedCost=consumedLiters*weightedPrice,remainingLiters=Math.max(0,suppliedLiters-consumedLiters),remainingValue=remainingLiters*weightedPrice,fuelCostForProfit=consumedLiters>0?consumedCost:gas+alcohol,maintenanceTotal=maintenanceItems.reduce((a,m)=>a+toNumber(m.value),0),extrasSum=extras.reduce((a,e)=>a+toNumber(e.value),0),totalExpenses=fuelCostForProfit+maintenanceTotal+extrasSum,dayProfit=fareNet-totalExpenses,totalCostPerKm=kmDriven>0?totalExpenses/kmDriven:null,profitPerKm=kmDriven>0?dayProfit/kmDriven:null,profitPerHour=hours>0?dayProfit/hours:null,gasCostPerKm=computeFuelCostPerKm(gas,kmDriven),alcoholCostPerKm=computeFuelCostPerKm(alcohol,kmDriven),fuelCostPerKm=kmDriven>0?fuelCostForProfit/kmDriven:0,hasCurrent=fareNet!==0||gas!==0||alcohol!==0||maintenanceTotal!==0||extrasSum!==0||kmDriven>0;
 const visibleProfit=savedCard&&!hasCurrent?savedCard.profit:dayProfit,visibleKm=savedCard&&!hasCurrent?savedCard.km:kmDriven,visibleProfitKm=savedCard&&!hasCurrent?savedCard.profitPerKm:profitPerKm,visibleCostKm=savedCard&&!hasCurrent?savedCard.costPerKm:totalCostPerKm,visibleHours=savedCard&&!hasCurrent?savedCard.hours:hours,currentVerdict=verdict(visibleProfit,visibleKm,visibleProfitKm,visibleCostKm,Boolean(savedCard)||hasCurrent);
 async function handleSubmit(e:React.FormEvent){e.preventDefault();if(kmFinal<kmInitial){setStatus("❌ O km final não pode ser menor que o km inicial.");return;}if(gas>0&&gasPrice<=0){setStatus("❌ Informe o preço por litro da gasolina.");return;}if(alcohol>0&&alcoholPrice<=0){setStatus("❌ Informe o preço por litro do álcool.");return;}if((gas>0||alcohol>0)&&kmDriven>0&&consumption<=0){setStatus("❌ Informe o consumo médio do veículo (Km/L).");return;}setStatus("Salvando...");const payload={date,gross_amount:mode==="withFee"?gross:null,fee_percent:mode==="withFee"?fee:null,net_fare:mode==="net"?netFare:null,gas_expense:gas,alcohol_expense:alcohol,gasoline_price_per_liter:gasPrice,alcohol_price_per_liter:alcoholPrice,gasoline_liters:gasLiters,alcohol_liters:alcoholLiters,km_initial:kmInitial,km_final:kmFinal,km_driven:kmDriven,hours_worked:hours,maintenance_expense:maintenanceTotal,maintenance_details:maintenanceItems.filter(m=>m.description.trim()!==""),extra_expenses:extras.filter(e=>e.name.trim()!==""),fuel_consumption_km_per_liter:consumption,fuel_consumed_liters:consumedLiters,fuel_consumed_cost:consumedCost,fuel_remaining_liters:remainingLiters,fuel_remaining_value:remainingValue};const res=await saveEntry(payload);if(res.success){setStatus("✅ Lançamento salvo com sucesso!");if(typeof res.monthProfit==="number")setMonthProfit(res.monthProfit);setSavedCard({profit:dayProfit,km:kmDriven,hours,profitPerKm,costPerKm:totalCostPerKm});setGross(0);setFee(0);setNetFare(0);setGas(0);setAlcohol(0);setGasPrice(0);setAlcoholPrice(0);setKmInitial(0);setKmFinal(0);setHours(0);setConsumption(0);setMaintenanceItems([]);setExtras([]);}else setStatus(`❌ Erro: ${res.error}`);}
 return <div className="space-y-5">{(!savedCard||hasCurrent)&&<StickyLaunchIntelligence profit={dayProfit} costs={totalExpenses} revenue={fareNet} gross={gross} km={kmDriven} hours={hours} feeAmount={feeAmount} profitPerKm={profitPerKm??undefined} profitPerHour={profitPerHour??undefined} fuelSpent={fuelCostForProfit} maintenance={maintenanceTotal} extras={extrasSum}/>}<form onSubmit={handleSubmit} className={`space-y-5 ${(!savedCard||hasCurrent)?"pt-[68px]":"pt-1"}`}>
 <div className="bg-white border border-slate-200 rounded-xl p-4 shadow-sm"><label className="label">Data do lançamento</label><input type="date" className="input max-w-xs" value={date} onChange={e=>setDate(e.target.value)} required/></div>
 <div className="bg-white border border-slate-200 rounded-xl p-4 shadow-sm space-y-3"><h3 className="text-sm font-semibold text-slate-700">Receita</h3><div className="flex flex-wrap gap-4"><label className="flex items-center gap-2 text-sm"><input type="radio" checked={mode==="withFee"} onChange={()=>setMode("withFee")}/>Valor com taxa</label><label className="flex items-center gap-2 text-sm"><input type="radio" checked={mode==="net"} onChange={()=>setMode("net")}/>Valor já líquido</label></div>{mode==="withFee"?<div className="grid grid-cols-1 sm:grid-cols-2 gap-3"><div><label className="label">Valor bruto (R$)</label><input type="number" step="0.01" min="0" className="input" value={gross||""} onChange={e=>setGross(toNumber(e.target.value))}/></div><div><label className="label">Taxa do app (%)</label><input type="number" step="0.01" min="0" max="100" className="input" value={fee||""} onChange={e=>setFee(toNumber(e.target.value))}/></div></div>:<div><label className="label">Valor líquido recebido (R$)</label><input type="number" step="0.01" min="0" className="input max-w-sm" value={netFare||""} onChange={e=>setNetFare(toNumber(e.target.value))}/></div>}<div className="rounded-lg border border-brand-200 bg-brand-50 p-3"><label className="label">Horas trabalhadas (opcional)</label><input type="number" step="0.1" min="0" className="input max-w-sm" value={hours||""} onChange={e=>setHours(toNumber(e.target.value))} placeholder="Ex.: 9"/></div></div>
 <div className="bg-white border border-slate-200 rounded-xl p-4 shadow-sm space-y-4"><div><h3 className="text-base font-bold text-slate-800">Quilometragem e combustível</h3><p className="text-xs text-slate-500 mt-1">O consumo médio permite separar o que foi abastecido do que realmente foi consumido para rodar os quilômetros do dia.</p></div><div className="grid grid-cols-1 sm:grid-cols-2 gap-3"><div><label className="label">Km inicial</label><input type="number" step="0.1" min="0" className="input" value={kmInitial||""} onChange={e=>setKmInitial(toNumber(e.target.value))}/></div><div><label className="label">Km final</label><input type="number" step="0.1" min="0" className="input" value={kmFinal||""} onChange={e=>setKmFinal(toNumber(e.target.value))}/></div></div><div className="rounded-xl border border-emerald-200 bg-emerald-50 p-4"><label className="label">Consumo médio do veículo (Km/L)</label><input type="number" step="0.1" min="0" className="input max-w-sm" value={consumption||""} onChange={e=>setConsumption(toNumber(e.target.value))} placeholder="Ex.: 10"/><p className="mt-1 text-xs text-slate-600">Informe quantos quilômetros o veículo faz com 1 litro do combustível utilizado.</p></div>
 <div className="border-t pt-4 space-y-3"><h4 className="font-semibold text-slate-700">Gasolina</h4><div className="grid grid-cols-1 sm:grid-cols-2 gap-3"><div><label className="label">Preço por litro (R$)</label><input type="number" step="0.001" min="0" className="input" value={gasPrice||""} onChange={e=>setGasPrice(toNumber(e.target.value))}/></div><div><label className="label">Quanto abasteceu (R$)</label><input type="number" step="0.01" min="0" className="input" value={gas||""} onChange={e=>setGas(toNumber(e.target.value))}/></div></div><div className="text-xs text-slate-500">{fmtL(gasLiters)} L abastecidos · {fmtCost(gasCostPerKm)} no abastecimento</div></div>
 <div className="border-t pt-4 space-y-3"><h4 className="font-semibold text-slate-700">Álcool</h4><div className="grid grid-cols-1 sm:grid-cols-2 gap-3"><div><label className="label">Preço por litro (R$)</label><input type="number" step="0.001" min="0" className="input" value={alcoholPrice||""} onChange={e=>setAlcoholPrice(toNumber(e.target.value))}/></div><div><label className="label">Quanto abasteceu (R$)</label><input type="number" step="0.01" min="0" className="input" value={alcohol||""} onChange={e=>setAlcohol(toNumber(e.target.value))}/></div></div><div className="text-xs text-slate-500">{fmtL(alcoholLiters)} L abastecidos · {fmtCost(alcoholCostPerKm)} no abastecimento</div></div>
 </div>
 <div className="bg-white border border-slate-200 rounded-xl p-4 shadow-sm"><MaintenanceExpenses items={maintenanceItems} onChange={setMaintenanceItems}/></div><div className="bg-white border border-slate-200 rounded-xl p-4 shadow-sm"><ExtraExpenses extras={extras} onChange={setExtras}/></div><button type="submit" className="btn btn-primary w-full">Salvar e ver meu lucro</button>{status&&<p className="text-sm text-center text-slate-600">{status}</p>}</form>
 <div className="space-y-4">{savedCard&&<><section className={`rounded-xl border p-5 shadow-sm ${currentVerdict.tone==="green"?"border-brand-200 bg-brand-50":currentVerdict.tone==="red"?"border-red-200 bg-red-50":currentVerdict.tone==="amber"?"border-amber-200 bg-amber-50":"border-slate-200 bg-slate-50"}`}><p className="text-xs font-bold uppercase tracking-wide text-slate-600">VEREDITO DO DIA</p><p className="mt-2 text-base font-semibold text-slate-800">{currentVerdict.text}</p></section><div className="grid grid-cols-1 sm:grid-cols-2 gap-4"><div className="bg-gradient-to-br from-brand-600 to-brand-700 text-white rounded-xl p-5 shadow-md"><p className="text-xs uppercase tracking-wide opacity-80">Lucro líquido do dia</p><p className="text-3xl font-bold mt-1">{formatBRL(visibleProfit)}</p><div className="text-xs opacity-90 mt-2 space-y-1">{visibleKm>0&&visibleProfitKm!==null&&<p><strong>{formatBRL(visibleProfitKm)}</strong> por km rodado</p>}{visibleHours>0&&<p><strong>{formatBRL(visibleProfit/visibleHours)}</strong> por hora</p>}</div></div><div className="bg-white border border-slate-200 rounded-xl p-5 shadow-sm"><p className="text-xs uppercase tracking-wide text-slate-500">Lucro líquido do mês</p><p className="text-3xl font-bold mt-1 text-slate-800">{formatBRL(monthProfit)}</p></div></div></>}</div>{savedCard&&<CardDeLucro profit={savedCard.profit} km={savedCard.km} profitPerHour={savedCard.hours>0?savedCard.profit/savedCard.hours:null} profitPerKm={savedCard.profitPerKm} costPerKm={savedCard.costPerKm} onClose={()=>setSavedCard(null)}/>}</div>;
}
