"use client";

import { useMemo, useState, type FormEvent } from "react";
import { formatBRL, toNumber, todayISO } from "@/lib/utils";
import { createRevenueItem, REVENUE_APPS, summarizeRevenue, type RevenueAppName, type RevenueItem } from "@/lib/revenue";
import ExtraExpenses from "./ExtraExpenses";
import MaintenanceExpenses, { type MaintenanceItem } from "./MaintenanceExpenses";
import CardDeLucro from "./CardDeLucro";
import { saveEntry } from "@/app/actions";

type Mode = "withFee" | "net";
type Props = { initialDate?: string; initialMonthProfit?: number };
type SavedCard = { profit:number; km:number; hours:number; profitPerKm:number|null; costPerKm:number|null; revenueBase:number };

function formatKm(v:number){return v.toLocaleString("pt-BR",{maximumFractionDigits:1});}
function formatCostPerKm(v:number|null){return v===null?"—":`${formatBRL(v)} / km`;}
function formatLiters(v:number){return v.toLocaleString("pt-BR",{minimumFractionDigits:2,maximumFractionDigits:3});}
function formatPercent(v:number){return `${v.toLocaleString("pt-BR",{minimumFractionDigits:1,maximumFractionDigits:1})}%`;}
function percentageText(profitPercent:number|null){if(profitPercent===null)return "";if(profitPercent>0)return ` Isso representa ${formatPercent(profitPercent)} de lucro sobre a receita líquida.`;if(profitPercent<0)return ` Isso representa um prejuízo de ${formatPercent(Math.abs(profitPercent))} sobre a receita líquida.`;return " Resultado de 0,0% sobre a receita líquida.";}
function verdict(profit:number,km:number,profitPerKm:number|null,costPerKm:number|null,hasLaunch:boolean,profitPercent:number|null){
 const percent=percentageText(profitPercent);
 if(!hasLaunch)return {tone:"neutral",text:"Lance o dia e descubra se sobrou dinheiro de verdade."};
 if(profit<=0){if(profit===0)return {tone:"amber",text:`🟡 Hoje você ficou no zero a zero: trabalhou pra pagar o carro.${percent}`};let text=`🔴 Hoje você PAGOU PRA TRABALHAR: faltaram ${formatBRL(Math.abs(profit))}.`;if(km>0&&profitPerKm!==null&&costPerKm!==null)text+=` Você ganhou ${formatBRL(profitPerKm)}/km e gastou ${formatBRL(costPerKm)}/km.`;return {tone:"red",text:text+percent};}
 if(km===0||profitPerKm===null||costPerKm===null||profitPerKm>=costPerKm){let text=`🟢 Hoje você LUCROU ${formatBRL(profit)}.`;if(km>0&&profitPerKm!==null&&costPerKm!==null)text+=` Você ganhou ${formatBRL(profitPerKm)}/km e gastou ${formatBRL(costPerKm)}/km.`;return {tone:"green",text:text+percent};}
 return {tone:"amber",text:`🟡 Hoje você LUCROU ${formatBRL(profit)}, mas atenção: ganhou ${formatBRL(profitPerKm)}/km e gastou ${formatBRL(costPerKm)}/km. Cuidado para não virar prejuízo.${percent}`};
}

export default function EntryForm({initialDate=todayISO(),initialMonthProfit=0}:Props){
 const [mode,setMode]=useState<Mode>("withFee"),[date,setDate]=useState(initialDate),[netFare,setNetFare]=useState(0),[revenueItems,setRevenueItems]=useState<RevenueItem[]>([createRevenueItem()]),[gas,setGas]=useState(0),[alcohol,setAlcohol]=useState(0),[gasPrice,setGasPrice]=useState(0),[alcoholPrice,setAlcoholPrice]=useState(0),[kmInitial,setKmInitial]=useState(0),[kmFinal,setKmFinal]=useState(0),[fuelConsumption,setFuelConsumption]=useState(0),[hours,setHours]=useState(0),[maintenanceItems,setMaintenanceItems]=useState<MaintenanceItem[]>([]),[extras,setExtras]=useState<{name:string;value:number}[]>([]),[monthProfit,setMonthProfit]=useState(initialMonthProfit),[status,setStatus]=useState(""),[savedCard,setSavedCard]=useState<SavedCard|null>(null);

 const revenueSummary=useMemo(()=>summarizeRevenue(revenueItems),[revenueItems]);
 const fareNet=mode==="withFee"?revenueSummary.liquido:netFare;
 const feeAmount=mode==="withFee"?revenueSummary.taxaValor:0;
 const extrasSum=extras.reduce((a,e)=>a+toNumber(e.value),0);
 const maintenanceTotal=maintenanceItems.reduce((a,m)=>a+toNumber(m.value),0);
 const kmDriven=Math.max(0,kmFinal-kmInitial);
 const gasLiters=gasPrice>0?gas/gasPrice:0;
 const alcoholLiters=alcoholPrice>0?alcohol/alcoholPrice:0;
 const totalPurchasedLiters=gasLiters+alcoholLiters;
 const totalFuelPurchase=gas+alcohol;
 const weightedFuelPrice=totalPurchasedLiters>0?totalFuelPurchase/totalPurchasedLiters:0;
 const fuelPrice=fuelConsumption>0?(gas>0&&gasPrice>0?gasPrice:alcohol>0&&alcoholPrice>0?alcoholPrice:weightedFuelPrice):0;
 const fuelConsumedLiters=kmDriven>0&&fuelConsumption>0?kmDriven/fuelConsumption:0;
 const fuelConsumedCost=fuelConsumedLiters*fuelPrice;
 const fuelRemainingLiters=Math.max(0,totalPurchasedLiters-fuelConsumedLiters);
 const fuelRemainingValue=fuelRemainingLiters*fuelPrice;
 const fuelCostForProfit=fuelConsumption>0&&totalPurchasedLiters>0?fuelConsumedCost:totalFuelPurchase;
 const totalExpenses=fuelCostForProfit+maintenanceTotal+extrasSum;
 const dayProfit=fareNet-totalExpenses;
 const totalCostPerKm=kmDriven>0?totalExpenses/kmDriven:null;
 const profitPerKm=kmDriven>0?dayProfit/kmDriven:null;
 const hasCurrentLaunch=fareNet!==0||totalFuelPurchase!==0||maintenanceTotal!==0||extrasSum!==0||kmDriven>0||fuelConsumption>0;
 const visibleProfit=savedCard&&!hasCurrentLaunch?savedCard.profit:dayProfit,visibleKm=savedCard&&!hasCurrentLaunch?savedCard.km:kmDriven,visibleProfitPerKm=savedCard&&!hasCurrentLaunch?savedCard.profitPerKm:profitPerKm,visibleCostPerKm=savedCard&&!hasCurrentLaunch?savedCard.costPerKm:totalCostPerKm,visibleHours=savedCard&&!hasCurrentLaunch?savedCard.hours:hours,visibleRevenueBase=savedCard&&!hasCurrentLaunch?savedCard.revenueBase:fareNet;
 const profitPercent=visibleRevenueBase>0?(visibleProfit/visibleRevenueBase)*100:null;
 const currentVerdict=verdict(visibleProfit,visibleKm,visibleProfitPerKm,visibleCostPerKm,Boolean(savedCard)||hasCurrentLaunch,profitPercent);

 function updateRevenue(id:string,patch:Partial<RevenueItem>){setRevenueItems(items=>items.map(item=>item.id===id?{...item,...patch}:item));}
 function addRevenue(){setRevenueItems(items=>[...items,createRevenueItem()]);}
 function removeRevenue(id:string){setRevenueItems(items=>items.length>1?items.filter(item=>item.id!==id):items);}

 async function handleSubmit(e:FormEvent){
  e.preventDefault();
  if(kmInitial<0||kmFinal<0||kmFinal<kmInitial||gas<0||alcohol<0||gasPrice<0||alcoholPrice<0||hours<0||fuelConsumption<0){setStatus("❌ Confira os quilômetros, as horas e os valores de combustível. Nenhum valor pode ser negativo e o km final deve ser maior ou igual ao inicial.");return;}
  if(gas>0&&gasPrice<=0){setStatus("❌ Informe o preço por litro da gasolina.");return;}
  if(alcohol>0&&alcoholPrice<=0){setStatus("❌ Informe o preço por litro do álcool.");return;}
  if(totalFuelPurchase>0&&kmDriven>0&&fuelConsumption<=0){setStatus("❌ Informe o consumo médio do veículo (Km/L).");return;}
  if(mode==="withFee"&&revenueSummary.normalized.some(item=>item.app==="Outro"&&!item.nomeAppPersonalizado)){setStatus("❌ Informe o nome do aplicativo quando selecionar Outro.");return;}
  setStatus("Salvando...");
  const payload={date,gross_amount:mode==="withFee"?revenueSummary.bruto:null,fee_percent:mode==="withFee"?revenueSummary.taxaPercentual:null,net_fare:mode==="net"?netFare:revenueSummary.liquido,revenue_details:mode==="withFee"?revenueItems:undefined,gas_expense:gas,alcohol_expense:alcohol,gasoline_price_per_liter:gasPrice,alcohol_price_per_liter:alcoholPrice,gasoline_liters:gasLiters,alcohol_liters:alcoholLiters,km_initial:kmInitial,km_final:kmFinal,km_driven:kmDriven,hours_worked:hours,fuel_consumption_km_per_liter:fuelConsumption,fuel_consumed_liters:fuelConsumedLiters,fuel_consumed_cost:fuelConsumedCost,fuel_remaining_liters:fuelRemainingLiters,fuel_remaining_value:fuelRemainingValue,maintenance_expense:maintenanceTotal,maintenance_details:maintenanceItems.filter(m=>m.description.trim()!==""),extra_expenses:extras.filter(e=>e.name.trim()!=="")};
  const res=await saveEntry(payload);
  if(res.success){setStatus("✅ Lançamento salvo com sucesso!");if(typeof res.monthProfit==="number")setMonthProfit(res.monthProfit);setSavedCard({profit:dayProfit,km:kmDriven,hours,profitPerKm,costPerKm:totalCostPerKm,revenueBase:fareNet});setNetFare(0);setRevenueItems([createRevenueItem()]);setGas(0);setAlcohol(0);setGasPrice(0);setAlcoholPrice(0);setKmInitial(0);setKmFinal(0);setFuelConsumption(0);setHours(0);setMaintenanceItems([]);setExtras([]);}else setStatus(`❌ Erro: ${res.error}`);
 }

 return <div className="space-y-5"><form onSubmit={handleSubmit} className="space-y-5">
  <div className="bg-white border border-slate-200 rounded-xl p-4 shadow-sm"><label className="label">Data do lançamento</label><input type="date" className="input max-w-xs" value={date} onChange={e=>setDate(e.target.value)} required/></div>
  <div className="bg-white border border-slate-200 rounded-xl p-4 shadow-sm space-y-4">
   <div><h3 className="text-sm font-semibold text-slate-700">Receita</h3><p className="mt-1 text-xs text-slate-500">Registre cada aplicativo separadamente. O FaturApp soma automaticamente as receitas líquidas do dia.</p></div>
   <div className="flex flex-wrap gap-4"><label className="flex items-center gap-2 text-sm cursor-pointer"><input type="radio" checked={mode==="withFee"} onChange={()=>setMode("withFee")}/>Valor bruto + taxa</label><label className="flex items-center gap-2 text-sm cursor-pointer"><input type="radio" checked={mode==="net"} onChange={()=>setMode("net")}/>Valor já líquido</label></div>
   {mode==="withFee"?<> <div className="space-y-3">{revenueItems.map((item,index)=><div key={item.id} className="rounded-2xl border border-slate-200 bg-slate-50/70 p-4 space-y-3">
     <div className="flex items-center justify-between gap-2"><div><p className="text-xs font-black uppercase tracking-wide text-slate-500">Receita {index+1}</p><p className="text-sm font-bold text-slate-800">Aplicativo</p></div>{revenueItems.length>1&&<button type="button" onClick={()=>removeRevenue(item.id)} className="rounded-lg bg-rose-50 px-3 py-2 text-xs font-bold text-rose-600">Remover</button>}</div>
     <div className="grid grid-cols-1 sm:grid-cols-3 gap-3"><div className="sm:col-span-1"><label className="label">Aplicativo</label><select className="input" value={item.app} onChange={e=>updateRevenue(item.id,{app:e.target.value as RevenueAppName,nomeAppPersonalizado:e.target.value==="Outro"?item.nomeAppPersonalizado:""})}>{REVENUE_APPS.map(app=><option key={app} value={app}>{app}</option>)}</select>{item.app==="Outro"&&<input className="input mt-2" value={item.nomeAppPersonalizado} onChange={e=>updateRevenue(item.id,{nomeAppPersonalizado:e.target.value})} placeholder="Nome do aplicativo regional"/>}</div><div><label className="label">Valor bruto (R$)</label><input type="number" step="0.01" min="0" className="input" value={item.bruto||""} onChange={e=>updateRevenue(item.id,{bruto:toNumber(e.target.value)})} placeholder="Ex.: 150,00"/></div><div><label className="label">Taxa do app (%)</label><input type="number" step="0.01" min="0" max="100" className="input" value={item.taxa||""} onChange={e=>updateRevenue(item.id,{taxa:toNumber(e.target.value)})} placeholder="Ex.: 20"/></div></div>
     <div className="flex flex-wrap items-center justify-between gap-2 rounded-xl border border-emerald-200 bg-emerald-50 px-3 py-2 text-sm"><span className="text-emerald-700">Líquido deste app</span><strong className="text-emerald-800">{formatBRL(summarizeRevenue([item]).liquido)}</strong></div>
   </div>)}</div>
   <button type="button" onClick={addRevenue} className="w-full rounded-xl border border-slate-300 bg-white px-4 py-3 text-sm font-bold text-slate-700 transition hover:border-emerald-400 hover:bg-emerald-50">+ Adicionar receita de outro App</button>
   <div className="rounded-2xl border border-emerald-200 bg-emerald-50 p-4 space-y-2"><div className="flex items-center justify-between"><span className="text-sm font-semibold text-emerald-700">Receita líquida total do dia</span><strong className="text-xl font-black text-emerald-800">{formatBRL(revenueSummary.liquido)}</strong></div><div className="flex justify-between border-t border-emerald-200 pt-2 text-xs text-emerald-700"><span>Bruto {formatBRL(revenueSummary.bruto)}</span><span>Taxas {formatBRL(revenueSummary.taxaValor)}</span></div></div></>:
   <div><label className="label">Valor líquido recebido (R$)</label><input type="number" step="0.01" min="0" className="input max-w-sm" value={netFare||""} onChange={e=>setNetFare(toNumber(e.target.value))} placeholder="Ex.: 250,00"/><p className="mt-1 text-xs text-slate-500">Use este modo quando o valor já estiver líquido das taxas.</p></div>}
   <div className="rounded-lg border border-brand-200 bg-brand-50 p-3"><label className="label">Horas trabalhadas (opcional)</label><input type="number" inputMode="decimal" step="0.1" min="0" className="input max-w-sm" value={hours||""} onChange={e=>setHours(toNumber(e.target.value))} placeholder="Ex: 9"/><p className="mt-1 text-xs text-slate-500">Use para descobrir quanto sobrou por hora. Não é obrigatório.</p></div>
  </div>
  <div className="bg-white border border-slate-200 rounded-xl p-4 shadow-sm space-y-4"><div><h3 className="text-base font-bold text-slate-800">Quilometragem e combustível</h3><p className="text-xs text-slate-500 mt-1">Informe o hodômetro e o abastecimento. O consumo médio permite calcular quanto do combustível foi realmente consumido no percurso.</p></div><div className="grid grid-cols-1 sm:grid-cols-2 gap-3"><div><label className="label">Km inicial</label><input type="number" step="0.1" min="0" className="input" value={kmInitial||""} onChange={e=>setKmInitial(toNumber(e.target.value))} placeholder="Ex.: 52.340"/></div><div><label className="label">Km final</label><input type="number" step="0.1" min="0" className="input" value={kmFinal||""} onChange={e=>setKmFinal(toNumber(e.target.value))} placeholder="Ex.: 52.520"/></div></div><div className="rounded-lg bg-slate-50 border border-slate-200 p-3 flex items-center"><div><p className="text-xs text-slate-500">Quantidade de km rodados</p><p className="text-2xl font-bold text-slate-800">{formatKm(kmDriven)} km</p></div></div>
   <div className="rounded-lg border border-brand-200 bg-brand-50 p-4"><label className="label">Consumo médio do veículo (Km/L)</label><input type="number" inputMode="decimal" step="0.1" min="0" className="input max-w-sm" value={fuelConsumption||""} onChange={e=>setFuelConsumption(toNumber(e.target.value))} placeholder="Ex.: 10"/><p className="mt-1 text-xs text-slate-500">Informe quantos quilômetros o veículo faz com 1 litro. Ex.: 10 km/L.</p></div>
   <div className="border-t border-slate-200 pt-4 space-y-3"><h4 className="font-semibold text-slate-700">Gasolina</h4><div className="grid grid-cols-1 sm:grid-cols-2 gap-3"><div><label className="label">Preço da gasolina por litro (R$)</label><input type="number" step="0.001" min="0" className="input" value={gasPrice||""} onChange={e=>setGasPrice(toNumber(e.target.value))} placeholder="Ex.: 6,19"/></div><div><label className="label">Quanto colocou de gasolina (R$)</label><input type="number" step="0.01" min="0" className="input" value={gas||""} onChange={e=>setGas(toNumber(e.target.value))} placeholder="Ex.: 100,00"/></div></div><div className="grid grid-cols-1 sm:grid-cols-3 gap-3"><div className="rounded-lg bg-slate-50 border border-slate-200 p-3"><p className="text-xs text-slate-500">Litros abastecidos</p><p className="text-lg font-bold text-slate-800">{formatLiters(gasLiters)} L</p></div><div className="rounded-lg bg-slate-50 border border-slate-200 p-3"><p className="text-xs text-slate-500">Custo de cada km rodado</p><p className="text-lg font-bold text-slate-800">{formatCostPerKm(kmDriven>0&&fuelConsumption>0&&gasPrice>0?fuelConsumedLiters*gasPrice/kmDriven:null)}</p></div><div className="rounded-lg bg-slate-50 border border-slate-200 p-3"><p className="text-xs text-slate-500">Compra</p><p className="text-lg font-bold text-slate-800">{formatBRL(gas)}</p></div></div></div>
   <div className="border-t border-slate-200 pt-4 space-y-3"><h4 className="font-semibold text-slate-700">Álcool</h4><div className="grid grid-cols-1 sm:grid-cols-2 gap-3"><div><label className="label">Preço do álcool por litro (R$)</label><input type="number" step="0.001" min="0" className="input" value={alcoholPrice||""} onChange={e=>setAlcoholPrice(toNumber(e.target.value))} placeholder="Ex.: 4,39"/></div><div><label className="label">Quanto colocou de álcool (R$)</label><input type="number" step="0.01" min="0" className="input" value={alcohol||""} onChange={e=>setAlcohol(toNumber(e.target.value))} placeholder="Ex.: 80,00"/></div></div><div className="grid grid-cols-1 sm:grid-cols-3 gap-3"><div className="rounded-lg bg-slate-50 border border-slate-200 p-3"><p className="text-xs text-slate-500">Litros abastecidos</p><p className="text-lg font-bold text-slate-800">{formatLiters(alcoholLiters)} L</p></div><div className="rounded-lg bg-slate-50 border border-slate-200 p-3"><p className="text-xs text-slate-500">Custo de cada km rodado</p><p className="text-lg font-bold text-slate-800">{formatCostPerKm(kmDriven>0&&fuelConsumption>0&&alcoholPrice>0?fuelConsumedLiters*alcoholPrice/kmDriven:null)}</p></div><div className="rounded-lg bg-slate-50 border border-slate-200 p-3"><p className="text-xs text-slate-500">Compra</p><p className="text-lg font-bold text-slate-800">{formatBRL(alcohol)}</p></div></div></div>
   <div className="grid grid-cols-1 sm:grid-cols-2 gap-3 border-t border-slate-200 pt-4"><div className="rounded-lg bg-emerald-50 border border-emerald-200 p-3"><p className="text-xs text-slate-500">Gasto real do percurso</p><p className="text-xl font-bold text-slate-800">{fuelConsumedLiters>0?formatBRL(fuelConsumedCost):"—"}</p><p className="text-xs text-slate-500 mt-1">{fuelConsumedLiters>0?`${formatLiters(fuelConsumedLiters)} L consumidos`:"Informe km/L e abastecimento"}</p></div><div className="rounded-lg bg-blue-50 border border-blue-200 p-3"><p className="text-xs text-slate-500">Saldo restante de combustível</p><p className="text-xl font-bold text-slate-800">{totalPurchasedLiters>0?`${formatLiters(fuelRemainingLiters)} L`:"—"}</p><p className="text-xs text-slate-500 mt-1">{totalPurchasedLiters>0?formatBRL(fuelRemainingValue):"—"}</p></div></div></div>
  <div className="bg-white border border-slate-200 rounded-xl p-4 shadow-sm"><MaintenanceExpenses items={maintenanceItems} onChange={setMaintenanceItems}/></div><div className="bg-white border border-slate-200 rounded-xl p-4 shadow-sm"><ExtraExpenses extras={extras} onChange={setExtras}/></div><button type="submit" className="btn btn-primary w-full">Salvar e ver meu lucro</button>{status&&<p className="text-sm text-center text-slate-600">{status}</p>}
 </form>
 <div className="space-y-4"><section className={`rounded-xl border p-5 shadow-sm ${currentVerdict.tone==="green"?"border-brand-200 bg-brand-50":currentVerdict.tone==="red"?"border-red-200 bg-red-50":currentVerdict.tone==="amber"?"border-amber-200 bg-amber-50":"border-slate-200 bg-slate-50"}`} aria-live="polite"><p className="text-xs font-bold uppercase tracking-wide text-slate-600">VEREDITO DO DIA</p><p className="mt-2 text-base font-semibold text-slate-800">{currentVerdict.text}</p></section><div className="grid grid-cols-1 sm:grid-cols-2 gap-4"><div className="bg-gradient-to-br from-brand-600 to-brand-700 text-white rounded-xl p-5 shadow-md"><p className="text-xs uppercase tracking-wide opacity-80">Lucro líquido do dia</p><p className="text-3xl font-bold mt-1">{formatBRL(visibleProfit)}</p>{profitPercent!==null&&<p className="mt-1 text-sm font-semibold opacity-95">{profitPercent>0?`Margem de lucro: ${formatPercent(profitPercent)} sobre a receita líquida`:profitPercent<0?`Prejuízo: ${formatPercent(Math.abs(profitPercent))} da receita líquida`:"Resultado: 0,0% da receita líquida"}</p>}<div className="text-xs opacity-90 mt-2 space-y-1">{visibleKm>0&&visibleProfitPerKm!==null&&<p><strong>{formatBRL(visibleProfitPerKm)}</strong> por km rodado</p>}{visibleHours>0&&<p><strong>{formatBRL(visibleProfit/visibleHours)}</strong> por hora trabalhada</p>}</div></div><div className="bg-white border border-slate-200 rounded-xl p-5 shadow-sm"><p className="text-xs uppercase tracking-wide text-slate-500">Lucro líquido do mês</p><p className="text-3xl font-bold mt-1 text-slate-800">{formatBRL(monthProfit)}</p><p className="text-xs text-slate-500 mt-2">Soma dos lançamentos do mês selecionado</p></div></div></div>
 {savedCard&&<CardDeLucro profit={savedCard.profit} km={savedCard.km} profitPerHour={savedCard.hours>0?savedCard.profit/savedCard.hours:null} profitPerKm={savedCard.profitPerKm} costPerKm={savedCard.costPerKm} onClose={()=>setSavedCard(null)}/>}</div>;
}
